name: Deploy Lambda Function

on:
  push:
    branches: [main]
    paths:
      - "backend/lambdas/**"

jobs:
  deploy-lambdas:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy save-user-preferences Lambda
        run: |
          cd backend/lambdas/save-user-preferences
          zip -r function.zip index.js
          aws lambda update-function-code \
            --function-name save-user-preferences \
            --zip-file fileb://function.zip

      - name: Deploy get-user-preferences Lambda
        run: |
          cd backend/lambdas/get-user-preferences
          zip -r function.zip index.js
          aws lambda update-function-code \
            --function-name get-user-preferences \
            --zip-file fileb://function.zip
