name: Deploy Full Stack

on:
  push:
    branches: [main]
    tags: ["v*"]

jobs:
  deploy-lambdas:
    name: Deploy Lambda Functions
    uses: ./.github/workflows/deploy-lambdas.yml

  deploy-frontend:
    name: Deploy Frontend
    uses: ./.github/workflows/deploy-frontend.yml
    needs: deploy-lambdas
